apiVersion: v1
kind: ConfigMap
metadata:
  name: resolveops-config
  namespace: resolveops-ai-dev
data:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
  API_GATEWAY_URL: "http://api-gateway-service:8000"
  FRONTEND_URL: "http://frontend:3000"
